import {
  AiOutlineSun as Sun,
  AiOutlineMenu as Menu,
  AiOutlineClose as Close,
  AiOutlineLoading as Loading,
} from "react-icons/ai";
import { BiLogOut as Logout } from "react-icons/bi";
import { BsMoonStars as Moon } from "react-icons/bs";
import { CiSettings as Settings } from "react-icons/ci";
import {
  FaAngleDown as AngleDown,
  FaRegPaperPlane as PaperPlane,
  FaPlusCircle as PlusCircle,
  FaEye as Eye,
  FaEyeSlash as EyeSlash,
  FaArrowRight as ArrowRight,
  FaBrain as Brain,
  FaMapMarkedAlt as MapMarkedAlt,
  FaMagic as Magic,
  FaProjectDiagram as ProjectDiagram,
  FaComments as Comments,
  FaSyncAlt as SyncAlt,
  FaUser as User,
  FaHistory as History,
  FaRobot as Robot,
  FaDatabase as Database,
  FaShieldAlt as ShieldAlt,
  FaFileContract as FileContract,
  FaChevronRight as ChevronRight,
  FaArrowLeft as ArrowLeft,
  FaTrash as Trash,
} from "react-icons/fa";
import { IoColorPaletteOutline as Palette } from "react-icons/io5";
export {
  Moon,
  Sun,
  Menu,
  Close,
  PaperPlane,
  AngleDown,
  PlusCircle,
  Logout,
  Eye,
  EyeSlash,
  ArrowRight,
  Brain,
  MapMarkedAlt,
  Magic,
  ProjectDiagram,
  Comments,
  SyncAlt,
  Trash,
  User,
  History,
  Robot,
  Database,
  ShieldAlt,
  FileContract,
  ChevronRight,
  ArrowLeft,
  Settings,
  Loading,
  Palette,
};
